import { useCallback, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Printer } from "lucide-react";
import { createRoot, type Root } from "react-dom/client";
import { MarkdownContent } from "./MarkdownView";
import { useI18n } from "../hooks/useI18n";
import { usePlatform } from "../hooks/usePlatform";

interface ExportPdfButtonProps {
  content?: string;
  filePath?: string;
  title?: string;
  disabled?: boolean;
  loadContent?: () => Promise<string>;
}

function displayTitle(title?: string, filePath?: string) {
  const raw = title || filePath?.split("/").pop() || "GitMemo";
  return raw.replace(/\.(md|mdx|txt)$/i, "");
}

function waitForImages(container: HTMLElement) {
  const images = Array.from(container.querySelectorAll("img"));
  if (images.length === 0) return Promise.resolve();

  return Promise.all(
    images.map((image) => {
      if (image.complete) return Promise.resolve();
      return new Promise<void>((resolve) => {
        image.addEventListener("load", () => resolve(), { once: true });
        image.addEventListener("error", () => resolve(), { once: true });
      });
    }),
  );
}

async function printDocument() {
  try {
    await invoke("print_current_window");
  } catch {
    window.print();
  }
}

export function ExportPdfButton({ content = "", filePath, title, disabled = false, loadContent }: ExportPdfButtonProps) {
  const { t } = useI18n();
  const isMobile = usePlatform() === "mobile";
  const [printing, setPrinting] = useState(false);
  const documentTitle = useMemo(() => displayTitle(title, filePath), [filePath, title]);

  const handleExport = useCallback(async () => {
    if (disabled || printing) return;

    setPrinting(true);
    const previousTitle = document.title;
    const host = document.createElement("div");
    host.id = "gitmemo-print-root";
    document.body.appendChild(host);

    let root: Root | null = null;
    try {
      const exportContent = loadContent ? await loadContent() : content;
      if (!exportContent.trim()) return;

      document.title = documentTitle;
      root = createRoot(host);
      root.render(
        <article className="gitmemo-print-document markdown-body">
          <header className="gitmemo-print-header">
            <div className="gitmemo-print-heading">
              <h1>{documentTitle}</h1>
              {filePath ? <p>{filePath}</p> : null}
            </div>
            <div className="gitmemo-print-brand" aria-label="Generated by GitMemo">
              GitMemo
            </div>
          </header>
          <MarkdownContent content={exportContent} filePath={filePath} />
        </article>,
      );

      await new Promise((resolve) => window.setTimeout(resolve, 250));
      await waitForImages(host);
      await printDocument();
    } finally {
      window.setTimeout(() => {
        root?.unmount();
        host.remove();
        document.title = previousTitle;
        setPrinting(false);
      }, 2000);
    }
  }, [content, disabled, documentTitle, filePath, loadContent, printing]);

  const buttonDisabled = disabled || printing || (!loadContent && !content.trim());

  return (
    <button
      type="button"
      onClick={(e) => {
        e.stopPropagation();
        void handleExport();
      }}
      disabled={buttonDisabled}
      title={t("common.exportPdf")}
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
        minWidth: isMobile ? 38 : undefined,
        minHeight: isMobile ? 38 : undefined,
        padding: isMobile ? "8px 10px" : "5px 10px",
        borderRadius: 6,
        fontSize: 12,
        cursor: buttonDisabled ? "not-allowed" : "pointer",
        background: isMobile ? "transparent" : "var(--bg)",
        border: isMobile ? "none" : "1px solid var(--border)",
        color: "var(--text-secondary)",
        opacity: buttonDisabled ? 0.45 : 1,
        flexShrink: 0,
      }}
    >
      <Printer size={isMobile ? 16 : 12} />
      {!isMobile && t("common.exportPdf")}
    </button>
  );
}
