import { useCallback, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Printer } from "lucide-react";
import { flushSync } from "react-dom";
import { createRoot, type Root } from "react-dom/client";
import { MarkdownContent } from "./MarkdownView";
import { useI18n } from "../hooks/useI18n";
import { usePlatform } from "../hooks/usePlatform";

interface ExportPdfButtonProps {
  content?: string;
  filePath?: string;
  title?: string;
  disabled?: boolean;
  loadContent?: () => Promise<string>;
  variant?: "toolbar" | "menuItem";
}

function displayTitle(title?: string, filePath?: string) {
  const raw = title || filePath?.split("/").pop() || "GitMemo";
  return raw.replace(/\.(md|mdx|txt)$/i, "");
}

function waitForImages(container: HTMLElement) {
  const images = Array.from(container.querySelectorAll("img"));
  if (images.length === 0) return Promise.resolve();

  return Promise.all(
    images.map((image) => {
      if (image.complete) return Promise.resolve();
      return new Promise<void>((resolve) => {
        image.addEventListener("load", () => resolve(), { once: true });
        image.addEventListener("error", () => resolve(), { once: true });
      });
    }),
  );
}

async function printDocument() {
  try {
    await invoke("print_current_window");
  } catch {
    window.print();
  }
}

function waitForNextPaint() {
  return new Promise<void>((resolve) => {
    window.requestAnimationFrame(() => {
      window.requestAnimationFrame(() => resolve());
    });
  });
}

function waitForPrintCompletion(timeoutMs = 30000) {
  return new Promise<void>((resolve) => {
    let done = false;
    const media = window.matchMedia?.("print");

    const cleanup = () => {
      window.clearTimeout(timeout);
      window.removeEventListener("afterprint", finish);
      media?.removeEventListener?.("change", handleMediaChange);
    };
    const finish = () => {
      if (done) return;
      done = true;
      cleanup();
      resolve();
    };
    const handleMediaChange = (event: MediaQueryListEvent) => {
      if (!event.matches) finish();
    };
    const timeout = window.setTimeout(finish, timeoutMs);

    window.addEventListener("afterprint", finish);
    media?.addEventListener?.("change", handleMediaChange);
  });
}

export function ExportPdfButton({ content = "", filePath, title, disabled = false, loadContent, variant = "toolbar" }: ExportPdfButtonProps) {
  const { t } = useI18n();
  const isMobile = usePlatform() === "mobile";
  const [printing, setPrinting] = useState(false);
  const documentTitle = useMemo(() => displayTitle(title, filePath), [filePath, title]);

  const handleExport = useCallback(async () => {
    if (disabled || printing) return;

    setPrinting(true);
    const previousTitle = document.title;
    const host = document.createElement("div");
    host.id = "gitmemo-print-root";
    document.body.appendChild(host);

    let root: Root | null = null;
    try {
      const exportContent = loadContent ? await loadContent() : content;
      if (!exportContent.trim()) return;

      document.title = documentTitle;
      root = createRoot(host);
      flushSync(() => {
        root?.render(
          <article className="gitmemo-print-document markdown-body">
            <header className="gitmemo-print-header">
              <div className="gitmemo-print-heading">
                <h1>{documentTitle}</h1>
                {filePath ? <p>{filePath}</p> : null}
              </div>
              <div className="gitmemo-print-brand" aria-label="Generated by GitMemo">
                GitMemo
              </div>
            </header>
            <MarkdownContent content={exportContent} filePath={filePath} />
          </article>,
        );
      });

      await waitForNextPaint();
      await waitForImages(host);
      const waitForPrint = waitForPrintCompletion();
      await printDocument();
      await waitForPrint;
    } finally {
      root?.unmount();
      host.remove();
      document.title = previousTitle;
      setPrinting(false);
    }
  }, [content, disabled, documentTitle, filePath, loadContent, printing]);

  const buttonDisabled = disabled || printing || (!loadContent && !content.trim());

  const isMenuItem = variant === "menuItem";

  return (
    <button
      type="button"
      onClick={(e) => {
        e.stopPropagation();
        void handleExport();
      }}
      disabled={buttonDisabled}
      title={t("common.exportPdf")}
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: isMenuItem ? "flex-start" : "center",
        gap: isMenuItem ? 8 : 4,
        width: isMenuItem ? "100%" : undefined,
        minWidth: isMenuItem ? undefined : isMobile ? 38 : undefined,
        minHeight: isMenuItem ? undefined : isMobile ? 38 : undefined,
        padding: isMenuItem ? "8px 10px" : isMobile ? "8px 10px" : "5px 10px",
        borderRadius: isMenuItem ? 4 : 6,
        fontSize: 12,
        cursor: buttonDisabled ? "not-allowed" : "pointer",
        background: isMenuItem || isMobile ? "transparent" : "var(--bg)",
        border: isMenuItem || isMobile ? "none" : "1px solid var(--border)",
        color: "var(--text-secondary)",
        opacity: buttonDisabled ? 0.45 : 1,
        flexShrink: 0,
        lineHeight: 1.2,
        whiteSpace: "nowrap",
      }}
    >
      <Printer size={isMenuItem ? 14 : isMobile ? 16 : 12} />
      {(isMenuItem || !isMobile) && t("common.exportPdf")}
    </button>
  );
}
