#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DESKTOP_DIR="$ROOT_DIR/desktop"
ANDROID_DIR="$DESKTOP_DIR/src-tauri/gen/android"
APK_SOURCE="$ANDROID_DIR/app/build/outputs/apk/universal/release/app-universal-release.apk"
ANDROID_SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}"
VERSION="$(awk -F'"' '/^version = / { print $2; exit }' "$ROOT_DIR/Cargo.toml")"
VERSION_CODE="$(awk -F. '{ printf "%d%03d%03d", $1, $2, $3 }' <<<"$VERSION")"
APK_OUTPUT="$ANDROID_DIR/app/build/outputs/apk/universal/release/gitmemo-android-v${VERSION}-arm64-v8a-release.apk"
TAURI_PROPERTIES="$ANDROID_DIR/app/tauri.properties"

if [ -z "${JAVA_HOME:-}" ]; then
    if [ -x "/opt/homebrew/opt/openjdk@17/bin/java" ]; then
        export JAVA_HOME="/opt/homebrew/opt/openjdk@17"
    elif [ -x "/opt/homebrew/opt/openjdk@21/bin/java" ]; then
        export JAVA_HOME="/opt/homebrew/opt/openjdk@21"
    else
        echo "JAVA_HOME is not set and no Homebrew OpenJDK was found." >&2
        exit 1
    fi
fi

export ANDROID_HOME="$ANDROID_SDK"
export ANDROID_SDK_ROOT="$ANDROID_SDK"

find_aapt() {
    find "$ANDROID_SDK/build-tools" -type f -name aapt 2>/dev/null | sort | tail -n 1
}

apk_version_name() {
    local apk="$1"
    local aapt_bin
    aapt_bin="$(find_aapt)"
    if [ -z "$aapt_bin" ]; then
        echo "Unable to find Android aapt under $ANDROID_SDK/build-tools" >&2
        return 1
    fi
    "$aapt_bin" dump badging "$apk" 2>/dev/null \
        | sed -n "s/.*versionName='\([^']*\)'.*/\1/p" \
        | head -n 1
}

cat > "$TAURI_PROPERTIES" <<EOF
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=$VERSION
tauri.android.versionCode=$VERSION_CODE
EOF

rm -f "$APK_SOURCE" "$APK_OUTPUT"

cd "$DESKTOP_DIR"
pnpm tauri android build --apk --target aarch64

if [ ! -f "$APK_SOURCE" ]; then
    echo "Expected APK was not generated: $APK_SOURCE" >&2
    exit 1
fi

abis="$(
    unzip -Z1 "$APK_SOURCE" 2>/dev/null \
        | awk -F/ '$1 == "lib" && $2 != "" && $NF ~ /\.so$/ { print $2 }' \
        | sort -u \
        | paste -sd ',' -
)"

if [ "$abis" != "arm64-v8a" ]; then
    echo "Unexpected APK ABI list: ${abis:-none}" >&2
    exit 1
fi

apk_version="$(apk_version_name "$APK_SOURCE")"
if [ "$apk_version" != "$VERSION" ]; then
    echo "Unexpected APK versionName: ${apk_version:-unknown}, expected $VERSION" >&2
    exit 1
fi

cp "$APK_SOURCE" "$APK_OUTPUT"
echo "$APK_OUTPUT"
